/datum/caste_datum/panther
	caste_type = XENO_CASTE_PANTHER
	tier = 2

	melee_damage_lower = XENO_DAMAGE_TIER_2
	melee_damage_upper = XENO_DAMAGE_TIER_3
	melee_vehicle_damage = XENO_DAMAGE_TIER_2
	max_health = XENO_HEALTH_TIER_7
	plasma_gain = XENO_PLASMA_GAIN_TIER_1
	plasma_max = XENO_NO_PLASMA
	xeno_explosion_resistance = XENO_EXPLOSIVE_ARMOR_TIER_2
	armor_deflection = XENO_NO_ARMOR
	evasion = XENO_EVASION_NONE
	speed = XENO_SPEED_TIER_8

	behavior_delegate_type = /datum/behavior_delegate/panther_base

	deevolves_to = list(XENO_CASTE_RUNNER)
	caste_desc = "A fast, powerful backline combatant."
	evolves_to = list(XENO_CASTE_RAVAGER)

	minimum_evolve_time = 9 MINUTES

	minimap_icon = "lurker"

/mob/living/carbon/xenomorph/panther
	caste_type = XENO_CASTE_PANTHER
	name = XENO_CASTE_PANTHER
	desc = "A beefy, fast alien with sharp claws."
	icon_size = 64
	icon_state = "Panther Walking"
	plasma_types = list(PLASMA_CATECHOLAMINE)
	pixel_x = -16
	old_x = -16
	base_pixel_x = 0
	base_pixel_y = -20
	xenonid_pixel_x = -9
	tier = 2
	organ_value = 2000
	base_actions = list(
		/datum/action/xeno_action/onclick/xeno_resting,
		/datum/action/xeno_action/onclick/release_haul,
		/datum/action/xeno_action/watch_xeno,
		/datum/action/xeno_action/activable/tail_stab,
		/datum/action/xeno_action/activable/pounce/panther,
		//datum/action/xeno_action/activable/blood_maul,
		//datum/action/xeno_action/onclick/tailspin,
		//datum/action/xeno_action/onclick/adrenaline_evasion,
	)
	inherent_verbs = list(
		/mob/living/carbon/xenomorph/proc/vent_crawl,
	)

	tackle_min = 2
	tackle_max = 6

	icon_xeno = 'icons/mob/xenos/castes/tier_2/panther.dmi'
	icon_xenonid = null //'icons/mob/xenonids/castes/tier_2/panther.dmi' // Commenting this out for now

	weed_food_icon = 'icons/mob/xenos/weeds_64x64.dmi'
	weed_food_states = list("Runner_1","Runner_2","Runner_3")
	weed_food_states_flipped = list("Runner_1","Runner_2","Runner_3")

	skull = /obj/item/skull/runner
	pelt = /obj/item/pelt/runner

/datum/behavior_delegate/panther_base
	name = "Base panther Behavior Delegate"

	// Written Summary of how Panther works:
	// Panther has Adrenaline instead of Plasma. It is generated by attacking or moving near hostiles, and quickly drains when neither conditions are being fufilled.
	// Adrenaline is used to automatically empower abilities on use when the necessary threshold has been reached.
	// Additionally ability cooldowns are sped up proportionally to Adrenaline, up to 50%. If spore fruit has been eaten, it takes priority over this.
	// Adrenaline built up via hostile proximity will be based on number of hostiles nearby, up to a cap.

	/// How much Adrenaline do we have?
	var/current_adrenaline = 0
	/// Maximum Adrenaline possible.
	var/max_adrenaline = 1000
	/// Can we generate Adrenaline currently?
	var/can_build_adrenaline = TRUE

	/// Used to keep track of how much cooldown reduction Adrenaline is currently providing.
	var/adrenaline_cooldown_current = 0
	/// Used to keep track of how much cooldown reduction Adrenaline was providing last tick.
	var/adrenaline_cooldown_previous = 0

	/// How much Adrenaline is generated per slash.
	var/adrenaline_slash_buildup = 12
	/// The Adrenaline generation cap for passive generation.
	var/adrenaline_passive_cap = 35
	/// How much Adrenaline is lost when conditions go unfufilled.
	var/adrenaline_deterioration = -50

	/// The range hostiles need to be in for Adrenaline to start generating, determined via dview().
	var/adrenaline_passive_range = 5
	/// List of hostiles logged on this tick and added to valid_targets.
	var/list/currently_nearby_hostiles = list()
	/// List of targets that were logged the previous tick.
	var/list/previously_nearby_hostiles = list()
	/// List of hostiles used to determine, through length() how much Adrenaline should be generated or, if 0, when decay should start.
	var/list/valid_targets = list()

/datum/behavior_delegate/panther_base/append_to_stat()
	. = list()
	. += "Adrenaline: [current_adrenaline]/[max_adrenaline]"
	. += "Cooldown Reduction: [adrenaline_cooldown_current]%"

/datum/behavior_delegate/panther_base/proc/adrenaline_passive_functions()
	FOR_DVIEW(var/mob/living/carbon/nearby_mob, adrenaline_passive_range, bound_xeno, HIDE_INVISIBLE_OBSERVER)
		// If they are dead, they are not valid
		if(nearby_mob.stat == DEAD)
			continue
		// If we cannot harm them (i.e we are allied to them), they are not valid
		if(bound_xeno.can_not_harm(nearby_mob))
			continue
		// Add them to list of currently nearby hostiles for referancing later
		currently_nearby_hostiles.Add(nearby_mob)
		// If they are not already in valid_targets, add them
		if(!(nearby_mob in valid_targets))
			valid_targets.Add(nearby_mob)
	FOR_DVIEW_END

	// Now we check for hostiles that aren't in range anymore
	for(var/mob/living/carbon/nearby_mob in valid_targets)
		// If the mob is in previously_nearby and not in currently_nearby, it's not nearby anymore
		if((nearby_mob in previously_nearby_hostiles) && !(nearby_mob in currently_nearby_hostiles))
			valid_targets.Remove(nearby_mob)
		// Same thing if it's not in either
		if(!(nearby_mob in previously_nearby_hostiles) && !(nearby_mob in currently_nearby_hostiles))
			valid_targets.Remove(nearby_mob)

	var/final_amount = length(valid_targets) * 2
	// If there is nobody nearby, start deteriorating
	if(final_amount == 0)
		modify_adrenaline(adrenaline_deterioration)
	else
		if(final_amount > adrenaline_passive_cap)
			final_amount = adrenaline_passive_cap
		modify_adrenaline(round(final_amount))

	// Make sure to set up for the next tick
	previously_nearby_hostiles = currently_nearby_hostiles
	currently_nearby_hostiles.Cut()

/datum/behavior_delegate/panther_base/proc/modify_adrenaline(adrenaline_amount)
	if(!can_build_adrenaline)
		return

	current_adrenaline += adrenaline_amount
	if(current_adrenaline > max_adrenaline)
		current_adrenaline = max_adrenaline
	if(current_adrenaline < 0)
		current_adrenaline = 0

/datum/behavior_delegate/panther_base/proc/adrenaline_cooldown_reduction()
	// If spore fruit has been eaten it takes priority, so remove any previous CD reduction, reset it, and stop processing until there no long is any spore froot effect
	for(var/datum/effects/gain_xeno_cooldown_reduction_on_slash/fruit_cooldown in bound_xeno.effects_list)
		bound_xeno.cooldown_reduction_percentage -= adrenaline_cooldown_previous
		adrenaline_cooldown_previous = 0
		return

	// To make this process simple, remove the cooldown reduction previously provided
	bound_xeno.cooldown_reduction_percentage -= adrenaline_cooldown_previous
	// Now we divide current Adrenaline by 20 to get the current cooldown reduction
	adrenaline_cooldown_current = current_adrenaline / 20
	// Very unnecessary redundancy but in place should something horribly break itself and lead to more than 50%
	if(adrenaline_cooldown_current > 50)
		adrenaline_cooldown_current = 50
	// Then apply the cooldown reduction and throw it into previous
	bound_xeno.cooldown_reduction_percentage += adrenaline_cooldown_current
	adrenaline_cooldown_previous = adrenaline_cooldown_current

/datum/behavior_delegate/panther_base/on_life()
	adrenaline_passive_functions()
	adrenaline_cooldown_reduction()

	var/image/holder = bound_xeno.hud_list[SPECIAL_HUD]
	holder.overlays.Cut()
	var/percentage_acid = round((current_adrenaline / max_adrenaline) * 100, 10)
	if(percentage_acid)
		holder.overlays += image('icons/mob/hud/hud.dmi', "xenoenergy[percentage_acid]")

/datum/behavior_delegate/panther_base/melee_attack_additional_effects_self()
	..()

	if(!can_build_adrenaline)
		return

	modify_adrenaline(adrenaline_slash_buildup)

// Abilities summarised
// Pounce: Regular pounce ala Runner. Empowering increases attack speed to Runner levels for the duration of the targets stun.
// Blood Maul: Savagely bite the target, causing lots of forced bleeding. Empowering gains armor piercing and dazes.
// Tail Spin: Hit hostiles within 1 tile. Empowering injects a selected toxin reagent.
// Toggle Evasion: Very rapidly drains Adrenaline and halts buildup to greatly increase evasion and provide passthrough ala Dancer. No Empowering for obvious reasons.
// Select Toxin: Choose what toxin Tail Spin applies.

/datum/action/xeno_action/activable/pounce/panther/additional_effects(mob/living/living_mob)
	var/mob/living/carbon/xenomorph/xeno = owner
	if(!istype(xeno))
		return

	var/datum/behavior_delegate/panther_base/bedel = xeno.behavior_delegate
	if(bedel.current_adrenaline >= adrenaline_empowering)
		if(currently_empowered)

		bedel.modify_adrenaline(-adrenaline_empowering)
		xeno.attack_speed_modifier -= slash_speed_buff
		xeno.recalculate_speed()
		to_chat(xeno, SPAN_XENOHIGHDANGER("Adrenaline courses through our body as we pounce on [living_mob], sending us into a brief frenzy!"))
		addtimer(CALLBACK(src, PROC_REF(remove_slash_speed_buff)), knockdown_duration + 0.5 SECONDS)

/datum/action/xeno_action/activable/pounce/panther/proc/remove_slash_speed_buff()
	var/mob/living/carbon/xenomorph/xeno = owner
	if(!istype(xeno))
		return

	xeno.attack_speed_modifier += slash_speed_buff
	xeno.recalculate_speed()
